### ISSUE TITLE
Cannot Modify Header Information

### ISSUE THREAD

**Issue by brandonpence** [drebbits/acf-enhanced-message-field#1]
I'm now experiencing a weird issue with this plugin. When I'm editing a post type that includes a field with a Enhanced Message and I go to preview or publish the changes, I'm left with a white screen and the following message:

`Cannot modify header information - headers already sent by (output started at ..../wp-content/plugins/acf-enhanced-message-field/acf-enhanced-message-v5.php:108) in /wp-includes/pluggable.php on line 1171`

Thanks for the help!

BTW, I've cross posted this on <a href="https://wordpress.org/support/topic/cannot-modify-header-information-127?replies=1">WordPress.org</a> as well.

**Comment by brandonpence** [comment]
I've reached out a couple of times over at WP. If you're no longer supporting this plugin, simply let me know.

**Comment by drebbits** [comment]
Thanks for reporting here. This should be fixed in the recent version/release. If not please reach out again (sorry for taking too long to get back).
